POST http://127.0.0.1:8000/profile/change/password
Content-Type: multipart/form-data;boundary=----WebKitFormBoundry 

------WebKitFormBoundry
Content-Disposition: form-data; name="password"

password
------WebKitFormBoundry
Content-Disposition: form-data; name="newpassword"

newpassword
------WebKitFormBoundry





